### ISSUE TITLE
CommandClient sendCommand Error

### ISSUE THREAD

**Issue by jensck** [particle-iot/particle-android#58]
Original issue: https://github.com/particle-iot/spark-setup-android/issues/55

---

code
```
 commandClient = CommandClient.newClientUsingDefaultsForDevices(getApplicationContext(), SSID.from(wifiAdmin.getWifiInfo()));

 DeviceIdCommand.Response response = commandClient.sendCommand(
                        new DeviceIdCommand(), DeviceIdCommand.Response.class);
```  
Error
```
 Could not find Network for SSID SSID: Photon-7LXY, BSSID: e0:4f:43:2e:61:39, MAC: 02:00:00:00:00:00, Supplicant state: COMPLETED, RSSI: -25, Link speed: 65Mbps, Frequency: 2462MHz, Net ID: 18, Metered hint: false, score: 60
                                                                        io.particle.android.sdk.devicesetup.commands.NetworkBindingSocketFactory$SocketBindingException: Could not find Network for SSID SSID: Photon-7LXY, BSSID: e0:4f:43:2e:61:39, MAC: 02:00:00:00:00:00, Supplicant state: COMPLETED, RSSI: -25, Link speed: 65Mbps, Frequency: 2462MHz, Net ID: 18, Metered hint: false, score: 60
                                                                            at io.particle.android.sdk.devicesetup.commands.NetworkBindingSocketFactory.bindSocketToSoftAp(NetworkBindingSocketFactory.java:91)
                                                                            at io.particle.android.sdk.devicesetup.commands.NetworkBindingSocketFactory.buildSocket(NetworkBindingSocketFactory.java:78)
                                                                            at io.particle.android.sdk.devicesetup.commands.NetworkBindingSocketFactory.createSocket(NetworkBindingSocketFactory.java:46)
                                                                            at io.particle.android.sdk.devicesetup.commands.CommandClient.sendAndMaybeReceive(CommandClient.java:73)
                                                                            at io.particle.android.sdk.devicesetup.commands.CommandClient.sendCommand(CommandClient.java:62)
                                                                            at com.umarbhutta.xlightcompanion.bindDevice.BindDeviceWiFiActivity$initAPThread.run(BindDeviceWiFiActivity.java:545)
                                                                            at java.lang.Thread.run(Thread.java:762)
```
I sure connected photon wlan
Please help me. thanks.

**Comment by jensck** [comment]
No response on original bug, closing.
